export const GET_PHONES_REQUEST = 'GET_PHONES_REQUEST' as const;
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS' as const;
export const GET_PHONES_FAILURE = 'GET_PHONES_FAILURE' as const;

export const GET_PHONE_REQUEST = 'GET_PHONE_REQUEST' as const;
export const GET_PHONE_SUCCESS = 'GET_PHONE_SUCCESS' as const;
export const GET_PHONE_FAILURE = 'GET_PHONE_FAILURE' as const;

export const CREATE_PHONE_REQUEST = 'CREATE_PHONE_REQUEST' as const;
export const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS' as const;
export const CREATE_PHONE_FAILURE = 'CREATE_PHONE_FAILURE' as const;

export const DELETE_PHONE_REQUEST = 'DELETE_PHONE_REQUEST' as const;
export const DELETE_PHONE_SUCCESS = 'DELETE_PHONE_SUCCESS' as const;
export const DELETE_PHONE_FAILURE = 'DELETE_PHONE_FAILURE' as const;

export const UPDATE_PHONE_REQUEST = 'UPDATE_PHONE_REQUEST' as const;
export const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS' as const;
export const UPDATE_PHONE_FAILURE = 'UPDATE_PHONE_FAILURE' as const;